clc; 
clear all;
fm=5;
t=0:0.0001:1;
a1=sin(2*pi*fm*t);
subplot(4,1,1);
plot(t,a1);
xlabel ('time');
ylabel ('amplitude');
title('message signal');
f1=fm;
f2=2*fm;
f3=40*fm;
t1=0:1/f1:1;
a2=sin(2*pi*fm*t1);
subplot(4,1,2);
plot(t1,a2);
xlabel ('time');
ylabel ('amplitude');
title('under sampled signal');
t2=0:1/f2:1;
a3=sin(2*pi*fm*t2);
subplot(4,1,3);
plot(t2,a3);
xlabel ('time');
ylabel ('amplitude');
title('Nyquist rate');
t3=0:1/f3:1;
a4=sin(2*pi*fm*t3);
subplot(4,1,4);
plot(t3,a4);
xlabel ('time');
ylabel ('amplitude');
title('over sampled signal');
